development:
  adapter: postgresql
  encoding: unicode
  database: expertise_development
  pool: 5
  username: todizzle91
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: expertise_test
  pool: 5
  username: todizzle91
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: expertise_production
  pool: 5
  username: todizzle91
  password: password
